image: Visual Studio 2015   # на этом VM-образе установлены все Visual Studio с 2008 по 2015

init:
    # секция инициализации, исполняется до клонирования проекта
    # скорее всего, строчка ниже необязательна (так должно быть по умолчанию),
    # вместе с тем, она присутствует в официальных примерах, так что пусть будет:
    - git config --global core.autocrlf input

clone_folder: c:\projects\my-prj # выбираем локальную директорию для клонирования
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: false           # не останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    # будем гонять CI на amd64 и x86...
#    - x64
    - x86

# configuration:
#    # ... и в дебажной, и в релизной конфигурациях ...
#    - Debug
#    - Release

#environment:
#    matrix:
#        # ... на трёх студиях (2010, 2012, 2015)
#        - TOOLCHAIN: msvc10
#        - TOOLCHAIN: msvc12
#        - TOOLCHAIN: msvc14

install:
    # скрипт настройки среды и установки зависимостей:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

build_script:
    # скрипт сборки проекта:
    - cl /c /nologo /O2 /Wall /TC *.c
    - link testLab0.obj testDriver.obj /out:testLab0.exe
    - link testLab10.obj testDriver.obj /out:testLab10.exe
    - link testLab11.obj testDriver.obj /out:testLab11.exe
    - link testLab2.obj testDriver.obj /out:testLab2.exe
    - link testLab30.obj testDriver.obj /out:testLab30.exe
    - link testLab4.obj testDriver.obj /out:testLab4.exe
    - link testLab5.obj testDriver.obj /out:testLab5.exe
    - link testLab6.obj testDriver.obj /out:testLab6.exe
    - link testLab7.obj testDriver.obj /out:testLab7.exe
    - link testLab80.obj testDriver.obj /out:testLab80.exe
    - link testLab9.obj testDriver.obj /out:testLab9.exe

test_script:
    # скрипт тестирования проекта:
    - testLab0.exe lab0.exe
    - testLab10.exe lab10.exe
    - testLab11.exe lab11.exe
    - testLab2.exe lab2.exe
    - testLab30.exe lab30.exe
    - testLab4.exe lab4.exe
    - testLab5.exe lab5.exe
    - testLab6.exe lab6.exe
    - testLab7.exe lab7.exe
    - testLab80.exe lab80.exe
    - testLab9.exe lab9.exe

#artifacts:
#    - path: <local-package-path>
#      name: package_name

#deploy:
#    # выкладываем tagged-коммиты на GitHub Releases:
#    description: '$(APPVEYOR_REPO_TAG_NAME)'
#    provider: GitHub
#
#    auth_token:
#        secure: <encrypted-github-token>
#
#    artifact: package_name
#    force_update: true
#
#    on:
#        appveyor_repo_tag: true
